# Generated by Django 4.0.2 on 2022-03-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_review_review_user_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='num_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
