# Generated by Django 4.0.2 on 2022-03-02 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0005_watchlist_avg_rating_watchlist_num_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='num_ratings',
            new_name='number_rating',
        ),
    ]
